openapi: 3.0.0

info:
  title: 06-jobs-api

  contact: {}

  version: "1.0"

servers:
  - url: https://jobs-api-uj.herokuapp.com/api/v1

    variables: {}

paths:
  /auth/register:
    post:
      tags:
        - Auth

      summary: Register User

      operationId: RegisterUser

      parameters: []

      requestBody:
        description: ""

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"

            example:
              name: 123User

              email: 123User@gmail.com

              password: "123123"

        required: true

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security: []

  /auth/login:
    post:
      tags:
        - Auth

      summary: Login User

      operationId: LoginUser

      parameters: []

      requestBody:
        description: ""

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserRequest"

            example:
              email: 123User@gmail.com

              password: "123123"

        required: true

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security: []

  /jobs:
    post:
      tags:
        - Jobs

      summary: Create job

      operationId: Createjob

      parameters: []

      requestBody:
        description: ""

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatejobRequest"

            example:
              company: LG

              position: intern

        required: true

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

    get:
      tags:
        - Jobs

      summary: Get All jobs

      operationId: GetAlljobs

      parameters: []

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID

    get:
      tags:
        - Jobs

      summary: Get job

      operationId: Getjob

      parameters: []

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

    patch:
      tags:
        - Jobs

      summary: Update job

      operationId: Updatejob

      parameters: []

      requestBody:
        description: ""

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatejobRequest"

            example:
              company: Apple company

              position: Back-end-developer

        required: true

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

    delete:
      tags:
        - Jobs

      summary: Delete job

      operationId: Deletejob

      parameters: []

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest

      required:
        - name

        - email

        - password

      type: object

      properties:
        name:
          type: string

        email:
          type: string

        password:
          type: string

      example:
        name: 123User

        email: 123User@gmail.com

        password: "123123"

    LoginUserRequest:
      title: LoginUserRequest

      required:
        - email

        - password

      type: object

      properties:
        email:
          type: string

        password:
          type: string

      example:
        email: 123User@gmail.com

        password: "123123"

    CreatejobRequest:
      title: CreatejobRequest

      required:
        - company

        - position

      type: object

      properties:
        company:
          type: string

        position:
          type: string

      example:
        company: LG

        position: intern

    UpdatejobRequest:
      title: UpdatejobRequest

      required:
        - company

        - position

      type: object

      properties:
        company:
          type: string

        position:
          type: string

      example:
        company: Apple company

        position: Back-end-developer

  securitySchemes:
    bearer:
      type: http

      scheme: bearer

security: []

tags:
  - name: Auth

    description: ""

  - name: Jobs

    description: ""
